version: '3'
services:
    database:
        container_name: mysql
        image: mysql/mysql-server:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            -   ./docker/volumes/databases:/home/
        networks:
            network1:
                ipv4_address: 172.18.0.7
    scadalts:
        image: scadalts/scadalts:latest
        ports:
            - "10008:8080"
        depends_on:
            - database
        expose: ["8080", "8000"]
        links:
            - database:database
        networks:
            network1:
                ipv4_address: 172.18.0.8
networks:
    network1:
        name: swat
        external: true